name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 🔹 Backend
      - name: Instalar backend
        run: |
          cd backend
          rm -rf node_modules package-lock.json
          npm install

      - name: Test backend (Jest)
        run: |
          cd backend
          npm test

      # 🔹 Frontend
      - name: Instalar frontend
        run: |
          cd frontend
          npm install

      # 🔹 E2E (Playwright)
      - name: Instalar Playwright
        run: |
          cd e2e
          npm ci
          npx playwright install chromium--with-deps

      - name: Fix permissions
        run: chmod -R 755 e2e/node_modules/.bin

      - name: Run E2E tests
        run: |
          cd e2e
          npx playwright test